// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaEsporte.Dados;

#nullable disable

namespace SistemaEsporte.Migrations
{
    [DbContext(typeof(ContextoBanco))]
    partial class ContextoBancoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SistemaEsporte.Modelos.Partida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<int>("GolsTime1")
                        .HasColumnType("int");

                    b.Property<int>("GolsTime2")
                        .HasColumnType("int");

                    b.Property<int>("Time1Id")
                        .HasColumnType("int");

                    b.Property<int>("Time2Id")
                        .HasColumnType("int");

                    b.Property<int>("VencedorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Time1Id");

                    b.HasIndex("Time2Id");

                    b.ToTable("Partidas");
                });

            modelBuilder.Entity("SistemaEsporte.Modelos.PartidaTorneio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Concluida")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DataPartida")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EhBye")
                        .HasColumnType("bit");

                    b.Property<int>("Fase")
                        .HasColumnType("int");

                    b.Property<int?>("GolsTime1")
                        .HasColumnType("int");

                    b.Property<int?>("GolsTime1Volta")
                        .HasColumnType("int");

                    b.Property<int?>("GolsTime2")
                        .HasColumnType("int");

                    b.Property<int?>("GolsTime2Volta")
                        .HasColumnType("int");

                    b.Property<int?>("PosicaoProximaPartida")
                        .HasColumnType("int");

                    b.Property<int?>("ProximaPartidaId")
                        .HasColumnType("int");

                    b.Property<int>("Rodada")
                        .HasColumnType("int");

                    b.Property<int?>("Time1Id")
                        .HasColumnType("int");

                    b.Property<int?>("Time2Id")
                        .HasColumnType("int");

                    b.Property<int>("TorneioId")
                        .HasColumnType("int");

                    b.Property<int?>("VencedorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TorneioId");

                    b.ToTable("PartidasTorneio");
                });

            modelBuilder.Entity("SistemaEsporte.Modelos.Time", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EscudoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Pontuacao")
                        .HasColumnType("int");

                    b.Property<int>("TotalDerrotas")
                        .HasColumnType("int");

                    b.Property<int>("TotalEmpates")
                        .HasColumnType("int");

                    b.Property<int>("TotalGolsMarcados")
                        .HasColumnType("int");

                    b.Property<int>("TotalGolsSofridos")
                        .HasColumnType("int");

                    b.Property<int>("TotalVitorias")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Times");
                });

            modelBuilder.Entity("SistemaEsporte.Modelos.Torneio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassificadosPorGrupo")
                        .HasColumnType("int");

                    b.Property<string>("CodigoConvite")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("Formato")
                        .HasColumnType("int");

                    b.Property<int>("MaxTimes")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumeroGrupos")
                        .HasColumnType("int");

                    b.Property<int>("RodadaAtual")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TimesPorGrupo")
                        .HasColumnType("int");

                    b.Property<int>("TotalRodadas")
                        .HasColumnType("int");

                    b.Property<int?>("VencedorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CodigoConvite")
                        .IsUnique()
                        .HasFilter("[CodigoConvite] IS NOT NULL");

                    b.ToTable("Torneios");
                });

            modelBuilder.Entity("SistemaEsporte.Modelos.TorneioTime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Derrotas")
                        .HasColumnType("int");

                    b.Property<int>("Empates")
                        .HasColumnType("int");

                    b.Property<int>("GolsMarcados")
                        .HasColumnType("int");

                    b.Property<int>("GolsSofridos")
                        .HasColumnType("int");

                    b.Property<string>("Grupo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeConvidado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PartidasJogadas")
                        .HasColumnType("int");

                    b.Property<int>("Pontos")
                        .HasColumnType("int");

                    b.Property<int>("SaldoGols")
                        .HasColumnType("int");

                    b.Property<int?>("TimeId")
                        .HasColumnType("int");

                    b.Property<int>("TorneioId")
                        .HasColumnType("int");

                    b.Property<int>("Vitorias")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TimeId");

                    b.HasIndex("TorneioId");

                    b.ToTable("TorneioTimes");
                });

            modelBuilder.Entity("SistemaEsporte.Modelos.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("EmailConfirmado")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ExpiracaoTokenConfirmacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpiracaoTokenRedefinicao")
                        .HasColumnType("datetime2");

                    b.Property<string>("HashSenha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Papel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TimeId")
                        .HasColumnType("int");

                    b.Property<string>("TokenConfirmacaoEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TokenRedefinicaoSenha")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("NomeUsuario")
                        .IsUnique();

                    b.HasIndex("TimeId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("SistemaEsporte.Modelos.Partida", b =>
                {
                    b.HasOne("SistemaEsporte.Modelos.Time", "Time1")
                        .WithMany()
                        .HasForeignKey("Time1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaEsporte.Modelos.Time", "Time2")
                        .WithMany()
                        .HasForeignKey("Time2Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Time1");

                    b.Navigation("Time2");
                });

            modelBuilder.Entity("SistemaEsporte.Modelos.PartidaTorneio", b =>
                {
                    b.HasOne("SistemaEsporte.Modelos.Torneio", "Torneio")
                        .WithMany("Partidas")
                        .HasForeignKey("TorneioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Torneio");
                });

            modelBuilder.Entity("SistemaEsporte.Modelos.TorneioTime", b =>
                {
                    b.HasOne("SistemaEsporte.Modelos.Time", "Time")
                        .WithMany()
                        .HasForeignKey("TimeId");

                    b.HasOne("SistemaEsporte.Modelos.Torneio", "Torneio")
                        .WithMany("Times")
                        .HasForeignKey("TorneioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Time");

                    b.Navigation("Torneio");
                });

            modelBuilder.Entity("SistemaEsporte.Modelos.Usuario", b =>
                {
                    b.HasOne("SistemaEsporte.Modelos.Time", "Time")
                        .WithMany()
                        .HasForeignKey("TimeId");

                    b.Navigation("Time");
                });

            modelBuilder.Entity("SistemaEsporte.Modelos.Torneio", b =>
                {
                    b.Navigation("Partidas");

                    b.Navigation("Times");
                });
#pragma warning restore 612, 618
        }
    }
}
